### ISSUE TITLE
Failing to Scrape Senators

### ISSUE THREAD

**Issue by mcrowson** [neelsomani/senator-filings#2] opened 2020-05-11 17:51 UTC
Trying to run the main.py file and getting the following:

```python
Traceback (most recent call last):
  File "main.py", line 182, in <module>
    senator_txs = main()
  File "main.py", line 156, in main
    set_search_results_layout(driver)
  File "main.py", line 85, in set_search_results_layout
    header = c.get_attribute(INNER_TEXT)
  File "/home/matthew/Documents/senator-filings/env/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 139, in get_attribute
    attributeValue = self.parent.execute_script(
  File "/home/matthew/Documents/senator-filings/env/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "/home/matthew/Documents/senator-filings/env/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/matthew/Documents/senator-filings/env/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 241, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: DataTables warning: table id=filedReports - Ajax error. For more information about this error, please see http://datatables.net/tn/7
Message: unexpected alert open: {Alert text : DataTables warning: table id=filedReports - Ajax error. For more information about this error, please see http://datatables.net/tn/7}
  (Session info: chrome=81.0.4044.138)
```

Running latest Chromium (rather than the supplied `chromedriver`) on Arch Linux

**Comment by neelsomani** [comment] 2020-05-11 18:40
Hmm, were you able to reproduce the error? Looks like there is some sort of AJAX failure and an alert is popping up for you.

**Comment by neelsomani** [comment] 2020-05-15 10:59
Hi @mcrowson, let me know if you're still having issues. I'll close this issue in the meantime but feel free to open again.

**Closed as completed by neelsomani** 2020-05-15 10:59 UTC

**Comment by mcrowson** [comment] 2020-05-15 11:01
Feel free to close. Haven’t had a chance to dig deeper. If others can do it, it is likely that I got a random pop up or just having a different browser was the issue.
